export const Users = [
  {
    id: 1,
    name: 'Aarav Sharma',
    age: 22,
    city: 'Mumbai',
    email: 'aarav1@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 2,
    name: 'Diya Patel',
    age: 25,
    city: 'Ahmedabad',
    email: 'diya2@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 3,
    name: 'Rohan Mehta',
    age: 28,
    city: 'Delhi',
    email: 'rohan3@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 4,
    name: 'Ishita Verma',
    age: 21,
    city: 'Pune',
    email: 'ishita4@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 5,
    name: 'Karan Singh',
    age: 30,
    city: 'Jaipur',
    email: 'karan5@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 6,
    name: 'Meera Nair',
    age: 24,
    city: 'Bangalore',
    email: 'meera6@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 7,
    name: 'Arjun Rao',
    age: 27,
    city: 'Hyderabad',
    email: 'arjun7@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 8,
    name: 'Sneha Kapoor',
    age: 23,
    city: 'Chandigarh',
    email: 'sneha8@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 9,
    name: 'Vikram Joshi',
    age: 29,
    city: 'Indore',
    email: 'vikram9@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 10,
    name: 'Ananya Iyer',
    age: 26,
    city: 'Chennai',
    email: 'ananya10@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 11,
    name: 'Rahul Das',
    age: 31,
    city: 'Kolkata',
    email: 'rahul11@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 12,
    name: 'Priya Malhotra',
    age: 22,
    city: 'Lucknow',
    email: 'priya12@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 13,
    name: 'Aditya Kulkarni',
    age: 28,
    city: 'Nagpur',
    email: 'aditya13@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 14,
    name: 'Neha Reddy',
    age: 24,
    city: 'Vijayawada',
    email: 'neha14@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 15,
    name: 'Manish Gupta',
    age: 33,
    city: 'Bhopal',
    email: 'manish15@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 16,
    name: 'Pooja Chawla',
    age: 27,
    city: 'Amritsar',
    email: 'pooja16@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 17,
    name: 'Siddharth Jain',
    age: 29,
    city: 'Noida',
    email: 'siddharth17@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 18,
    name: 'Kavya Menon',
    age: 23,
    city: 'Kochi',
    email: 'kavya18@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 19,
    name: 'Harsh Vardhan',
    age: 26,
    city: 'Patna',
    email: 'harsh19@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
  {
    id: 20,
    name: 'Tanvi Desai',
    age: 25,
    city: 'Surat',
    email: 'tanvi20@example.com',
    skill: 'JavaScript',
    education: 'Information Technology',
  },
]
