export const defaultUsers = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    gender: 'male',
    skills: ['HTML', 'CSS'],
    role: 'frontend',
    phone: '9999999999',
    experience: '2',
    age: '25',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@gmail.com',
    gender: 'female',
    skills: ['React'],
    role: 'backend',
    phone: '8888888888',
    experience: '3',
    age: '28',
  },
  {
    id: 3,
    name: 'Alex',
    email: 'alex@gmail.com',
    gender: 'male',
    skills: ['JS'],
    role: 'fullstack',
    phone: '7777777777',
    experience: '1',
    age: '22',
  },
]
