export const PRODUCTS = [
  {
    id: 1,
    name: 'iPhone 15',
    description: 'Latest Apple smartphone',
    price: 899,
    brand: 'Apple',
    category: 'Smartphones',
    stock: 25,
    rating: 4.8,
    reviews: 1200,
    image: 'https://example.com/iphone15.jpg',
    isFeatured: true,
  },
  {
    id: 2,
    name: 'MacBook Pro',
    description: 'Powerful laptop for developers',
    price: 2000,
    brand: 'Apple',
    category: 'Laptops',
    stock: 10,
    rating: 4.9,
    reviews: 850,
    image: 'https://example.com/macbookpro.jpg',
    isFeatured: true,
  },
  {
    id: 3,
    name: 'Samsung Galaxy S24',
    description: 'High-end Android smartphone',
    price: 799,
    brand: 'Samsung',
    category: 'Smartphones',
    stock: 30,
    rating: 4.7,
    reviews: 950,
    image: 'https://example.com/galaxy-s24.jpg',
    isFeatured: false,
  },
  {
    id: 4,
    name: 'Dell XPS 13',
    description: 'Compact and powerful ultrabook',
    price: 1500,
    brand: 'Dell',
    category: 'Laptops',
    stock: 15,
    rating: 4.6,
    reviews: 600,
    image: 'https://example.com/dell-xps13.jpg',
    isFeatured: false,
  },
  {
    id: 5,
    name: 'Sony WH-1000XM5',
    description: 'Noise-cancelling wireless headphones',
    price: 350,
    brand: 'Sony',
    category: 'Accessories',
    stock: 50,
    rating: 4.8,
    reviews: 2000,
    image: 'https://example.com/sony-headphones.jpg',
    isFeatured: true,
  },
  {
    id: 6,
    name: 'iPad Air',
    description: 'Lightweight tablet with powerful performance',
    price: 699,
    brand: 'Apple',
    category: 'Tablets',
    stock: 20,
    rating: 4.7,
    reviews: 500,
    image: 'https://example.com/ipad-air.jpg',
    isFeatured: false,
  },
]
