export const PRODUCTS = [
  {
    id: 1,
    name: 'iPhone 15',
    description: 'Latest Apple smartphone',
    stock: 25,
    isFeatured: true,
  },
  {
    id: 2,
    name: 'MacBook Pro',
    description: 'Powerful laptop',
    stock: 5,
    isFeatured: true,
  },
  {
    id: 3,
    name: 'Samsung S24',
    description: 'Android flagship',
    stock: 0,
    isFeatured: false,
  },
  {
    id: 4,
    name: 'iPad Air',
    description: 'Lightweight tablet',
    stock: 12,
    isFeatured: false,
  },
  {
    id: 5,
    name: 'Sony WH-1000XM5',
    description: 'Noise cancelling headphones',
    stock: 30,
    isFeatured: true,
  },
  {
    id: 6,
    name: 'Dell XPS 13',
    description: 'Compact ultrabook',
    stock: 7,
    isFeatured: false,
  },
  {
    id: 7,
    name: 'Apple Watch Series 9',
    description: 'Smartwatch with fitness tracking',
    stock: 18,
    isFeatured: true,
  },
  {
    id: 8,
    name: 'Logitech MX Master 3',
    description: 'Advanced wireless mouse',
    stock: 40,
    isFeatured: false,
  },
  {
    id: 9,
    name: 'Samsung Galaxy Tab S9',
    description: 'High-performance Android tablet',
    stock: 0,
    isFeatured: false,
  },
  {
    id: 10,
    name: 'HP Pavilion Laptop',
    description: 'Affordable everyday laptop',
    stock: 20,
    isFeatured: false,
  },
]
